[tools]
"aqua:argoproj/argo-cd" = "3.3.2"
"aqua:aws/aws-cli" = "2.34.4"
"aqua:go-task/task" = "3.48.0"
"aqua:golang/go" = "1.26.1"
"aqua:gruntwork-io/terragrunt" = "0.99.4"
"aqua:hashicorp/terraform" = "1.14.6"
"aqua:jqlang/jq" = "1.8.1"
"aqua:mikefarah/yq" = "4.52.4"
